# NUMPY

In [3]:
# pip install numpy

In [4]:
import numpy
numpy.__version__

'1.15.1'

# ARRAY CREATION

In [7]:
import numpy as np
a=np.array([14,2,3,4,5,6,7])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)

[14  2  3  4  5  6  7]
<class 'numpy.ndarray'>
int32
(7,)


In [8]:
print(a[0])
a[2]=2
print(a)

14
[14  2  2  4  5  6  7]


In [9]:
a =  np.array([[1],[2],[3],[4]])
print(a)
print(a.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [10]:
a= np.array([[1,2,3,4]])
print(a)
print(a.shape)


[[1 2 3 4]]
(1, 4)


In [8]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(type(a))
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(2, 4)


In [12]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a[0,1])
a[0,3]=89
a[1,3]=100
print(a)
#print(a)

[[1 2 3 4]
 [5 6 7 8]]
2
[[  1   2   3  89]
 [  5   6   7 100]]


In [13]:
list1 = [1,2,3,4,5]
list2=[[1,2,3,4],[5,6,7,8]]
a= np.array(list1)
print(a)
print(a.shape)
b=np.array(list2)
print(b)
print(b.shape)

[1 2 3 4 5]
(5,)
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


# Array Functions

- Reshape

In [14]:
list1 = [1,2,3,4,5,6,7,8,9,10]
a=np.array(list1)
print(a)
print(a.reshape(2,5))
print(a.reshape(5,2))
print(a.reshape(2,-3))

#print(a.reshape(-2,-3))   will throw error


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
list1 = [1,2,3,4,5,6,7,8,9,10]
a=np.array(list1)
print(a)
b=a.reshape(2,5)
print(b)
print(b.ravel())   

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


- Tolist

In [30]:
list1 = [1,2,3,4,5,6,7,8,9,10]
a=np.array(list1)
print(a)
print(type(a))
b=a.tolist()
print(b)
print(type(b))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>


In [34]:
tuple1=(1,2,3,4,5,6,7,8,9,10)
a=np.array(tuple1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


# Data Type Conversion

In [38]:
import numpy  as np
x= np.array([1,2])
print(x)
print(x.dtype)

x= np.array([1.,2.])
print(x)
print(x.dtype)

x= np.array([2.3,2.3],dtype= float)
print(x)
print(x.dtype)

[1 2]
int32
[1. 2.]
float64
[2.3 2.3]
float64


## frequently used arrays

In [47]:
a= np.zeros((2,5))
print(a)
print(a.dtype)

a= np.zeros((2,5), dtype=int)
print(a)
print(a.dtype)

a= np.ones((2,5),dtype=int) 
print(a.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
[[0 0 0 0 0]
 [0 0 0 0 0]]
int32
int32


In [55]:
a= np.full((2,3),4)
print(a)
print(a.dtype)

b= np.full((2,3),4, dtype=float)
print(b)
print(b.dtype)


[[4 4 4]
 [4 4 4]]
int32
[[4. 4. 4.]
 [4. 4. 4.]]
float64


In [56]:
a= np.random.random((3,3))
print(a)

[[0.19427807 0.68731283 0.82289188]
 [0.96052083 0.25429473 0.78569669]
 [0.95320489 0.19779785 0.80398658]]


In [68]:
a=np.random.randint(5,15,size=(3,3)) #randdom numbers between 5 and 14
print(a) 
                    
                    

[[ 9  5 10]
 [ 7 12  6]
 [ 7  6  5]]


# Array Slicing

In [70]:
import numpy as np
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[0:2,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [73]:
import numpy as np
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

print(a[:1,:-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3]]


In [74]:
import numpy as np
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[::2,1::2])
print(a[:-1,::3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  4]
 [10 12]]
[[1 4]
 [5 8]]


In [77]:
import numpy as np
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=a[::2,1::2
   ]
print(b)
b[0,0]=99
print(b)
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [10 11]]
[[99  3]
 [10 11]]
[[ 1 99  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [78]:
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[:2,[0,1,3]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 4]
 [5 6 8]]


# Boolean Indexing

In [85]:
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=a>5
print(b)
print(a[b])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11 12]


# Array Operations

In [93]:
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])
print(a)
print(b)
print(a+b)
print(np.add(a,b))
print(a-b)
print(np.subtract(a,b))
print(a*b)
print(np.multiply(a,b))
print(a//b)
print(np.divide(a,b))
print(a**b)

             
             

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0 0]
 [0 0]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[    1    64]
 [ 2187 65536]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [94]:
print(np.sqrt(a))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [96]:
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])
v=np.array([9,10])
w=np.array([11,12])
print(a)
print(b)
print(v)
print(w)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 9 10]
[11 12]


In [99]:
print(v.dot(w))
#print(np.dot(v,w))   #2nd method

219


In [100]:
print(a)
print(np.sum(a))
print(np.sum(a, axis=1))
print(np.sum(a, axis=0))

[[1 2]
 [3 4]]
10
[3 7]
[4 6]


In [101]:
print(a)
print(a.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
